name: Create Branch

on:
  workflow_dispatch:
    inputs:
      project-id:
        description: 'Select a Project'
        required: true
        type: choice
        options:
          - branch-management-dev
          - branch-management-test
      name:
        description: 'Branch Name'
        required: true

defaults:
  run:
    working-directory: main

env:
  NEON_API_KEY: ${{ secrets.NEON_API_KEY }}

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Install Neon CLI
        run: npm install -g neonctl@latest

      - name: Verify Neon CLI install
        run: |
          neon --version

      - name: List Projects
        run: |
          neon projects list

      - name: Map Project Name to Project ID
        run: |
          declare -A PROJECT_NAME_TO_ID=(
            ["branch-management-dev"]="polished-water-58114712"
            ["branch-management-test"]="autumn-bush-97691534"
          )

          echo "PROJECT_ID=${PROJECT_NAME_TO_ID["${{ github.event.inputs.project-id }}"]}" >> $GITHUB_ENV

      - name: Create Branch
        run: |
          neon branches create --project-id "$PROJECT_ID" --name "${{ github.event.inputs.name }}"
