name: Create Branch

on:
  workflow_dispatch:
    inputs:
      project-id:
        description: 'Project ID'
        required: true
      name:
        description: 'Branch Name'
        required: true

env:
  NEON_API_KEY: ${{ secrets.NEON_API_KEY }}

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Install Neon CLI
        run: npm install -g neonctl@latest

      - name: Verify Neon CLI install
        run: |
          neon --version

      - name: List Projects
        run: |
          neon projects list

      - name: Create Branch
        run: |
          neon branches create --project-id "${{ github.event.inputs.project-id }}" --name "${{ github.event.inputs.name }}"
